#%RAML 1.0
title: weather-system
version: 1.0
description: Weather system API retrieves the weather details based on the postal code

traits:
  client-id-required:
    headers:
      client_id:
        type: string
      client_secret:
        type: string
    responses:
      401:
        description: Unauthorized or invalid client application credentials
      500:
        description: Bad response from authorization server, or WSDL SOAP Fault error
        
/weather:
 get:
  is: [client-id-required]
  queryParameters:
   postalcode:
    type: string
    required: true
  responses:
   200:
    body:
     application/json:
      example: !include weatherResponse.raml
   400:
    body:
     application/json: 
      example:
       {"message" : "Bad Request"}
   500:
    body:
     application/json:
      example:
        {"message" : "Internal Server Error"}